#!/bin/bash

# This file keeps the state of the
# widget. It also holds the last workspace
TOGGLEFILE="/tmp/eww.dashboard"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
    eww daemon
    sleep 1
fi

## Launch or close widgets accordingly
if [[ ! -f "$TOGGLEFILE" ]]; then
    touch "$TOGGLEFILE"

    # get current workspace and write it to the file
    hyprctl activewindow | grep "workspace: " | \
        cut -d' ' -f2 > "$TOGGLEFILE"
    # toggle to workspace 9
    hyprctl dispatch workspace 9

    eww open dashboard
else
    eww close dashboard

    # toggle back
    hyprctl dispatch workspace $(cat "$TOGGLEFILE")
    
    rm "$TOGGLEFILE"
fi