[package]
name = "widgetbuilder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
wayland = ["gtk-layer-shell"]

[dependencies]
gtk = "0.17.1"
gtk-layer-shell = { version = "0.6.1", optional = true }