#!/bin/bash

# Usage:
#       # Toggle the dashboard
#       dasbboard
#       # Close dashboard and dispatch cmd
#       dashboard <cmd>

# This file keeps the state of the
# widget. It also holds the last workspace
TOGGLEFILE="/tmp/eww.dashboard"
CONFIG="$HOME/.config/eww/dashboard"

run_daemon() {
    ## Run eww daemon if not running already
    if [[ ! `pidof eww` ]]; then
        eww -c "$CONFIG" daemon
        sleep 1
    fi
}

open_dashboard() {
    touch "$TOGGLEFILE"

    # get current workspace and write it to the file
    hyprctl activewindow | grep "workspace: " | \
        cut -d' ' -f2 > "$TOGGLEFILE"
    # toggle to first 9 workspace
    hyprctl dispatch workspace 9

    eww  -c "$CONFIG" open dashboard
}

close_dashboard() {
    eww -c "$CONFIG" close dashboard

    # toggle back
    hyprctl dispatch workspace $(cat "$TOGGLEFILE")
    
    rm "$TOGGLEFILE"
}

toggle_dashboard() {
    ## Launch or close widgets accordingly
    if [[ -f "$TOGGLEFILE" ]]; then
        close_dashboard
    else
        open_dashboard
    fi
}

if [ "$#" -gt 0 ]; then
    close_dashboard

    # Join all the arguments to form a command
    command="$*"
    # Execute the command using eval
    eval "$command"
else
    run_daemon
    toggle_dashboard
fi