#!/bin/bash

# Usage:
#       # Toggle the dashboard
#       dasbboard
#       # Close dashboard and dispatch cmd
#       dashboard <cmd>

# Keep track of the process PID
PIDFILE="/tmp/widgets.dashboard.pid"
# Keep track of the last workspace
WORKSPACEFILE="/tmp/widgets.dashboard.ws"

open_dashboard() {
    # get current workspace and write it to the file
    hyprctl activewindow | grep "workspace: " | \
        cut -d' ' -f2 > "$WORKSPACEFILE"
    # toggle to dashboard workspace
    hyprctl dispatch workspace name:Dashboard

    dashboard &
    pid=$!
    echo "$pid" > "$PIDFILE"
}

close_dashboard() {
    pid=$(cat "$PIDFILE")
    kill "$pid"

    # toggle back
    hyprctl dispatch workspace $(cat "$WORKSPACEFILE")
    
    rm "$PIDFILE"
}

toggle_dashboard() {
    ## Launch or close widgets accordingly
    if [[ -f "$PIDFILE" ]]; then
        close_dashboard
    else
        open_dashboard
    fi
}

if [ "$#" -gt 0 ]; then # I don't use this feature anymore (?)
    close_dashboard

    # Join all the arguments to form a command
    command="$*"
    # Execute the command using eval
    eval "$command"
else
    toggle_dashboard
fi