#!/bin/bash

## To update cache
## ~/.config/eww/scripts/weather_info --getdata

## Collect data
cache_dir="$HOME/.cache/eww/weather"
cache_weather_stat=${cache_dir}/weather-stat
cache_weather_degree=${cache_dir}/weather-degree
cache_weather_hex=${cache_dir}/weather-hex
cache_weather_icon=${cache_dir}/weather-icon
update_interval=15 # minutes

## Weather data
KEY="<key>" # Get your free key at api.openweathermap.org
CITY="London,uk"
UNITS="metric"

## Get data
update_weather_data() {
    weather=`curl -sf "http://api.openweathermap.org/data/2.5/weather?q="$CITY"&units="$UNITS"&appid="$KEY""`

    if [ ! -z "$weather" ]; then
        weather_temp=`echo "$weather" | jq ".main.temp" | cut -d "." -f 1`
        weather_icon_code=`echo "$weather" | jq -r ".weather[].icon" | head -1`
        weather_description=`echo "$weather" | jq -r ".weather[].description" | head -1 | sed -e "s/\b\(.\)/\u\1/g"`

        if [ "$weather_icon_code" == "50d"  ]; then
            weather_icon=" "
            weather_hex="#84afdb"
        elif [ "$weather_icon_code" == "50n"  ]; then
            weather_icon=" "
            weather_hex="#84afdb"
        elif [ "$weather_icon_code" == "01d"  ]; then
            weather_icon=" "
            weather_hex="#ffd86b"
        elif [ "$weather_icon_code" == "01n"  ]; then
            weather_icon=" "
            weather_hex="#fcdcf6"
        elif [ "$weather_icon_code" == "02d"  ]; then
            weather_icon=" "
            weather_hex="#adadff"
        elif [ "$weather_icon_code" == "02n"  ]; then
            weather_icon=" "
            weather_hex="#adadff"
        elif [ "$weather_icon_code" == "03d"  ]; then
            weather_icon=" "
            weather_hex="#adadff"
        elif [ "$weather_icon_code" == "03n"  ]; then
            weather_icon=" "
            weather_hex="#adadff"
        elif [ "$weather_icon_code" == "04d"  ]; then
            weather_icon=" "
            weather_hex="#adadff"
        elif [ "$weather_icon_code" == "04n"  ]; then
            weather_icon=" "
            weather_hex="#adadff"
        elif [ "$weather_icon_code" == "09d"  ]; then
            weather_icon=" "
            weather_hex="#6b95ff"
        elif [ "$weather_icon_code" == "09n"  ]; then
            weather_icon=" "
            weather_hex="#6b95ff"
        elif [ "$weather_icon_code" == "10d"  ]; then
            weather_icon=" "
            weather_hex="#6b95ff"
        elif [ "$weather_icon_code" == "10n"  ]; then
            weather_icon=" "
            weather_hex="#6b95ff"
        elif [ "$weather_icon_code" == "11d"  ]; then
            weather_icon=""
            weather_hex="#ffeb57"
        elif [ "$weather_icon_code" == "11n"  ]; then
            weather_icon=""
            weather_hex="#ffeb57"
        elif [ "$weather_icon_code" == "13d"  ]; then
            weather_icon=" "
            weather_hex="#e3e6fc"
        elif [ "$weather_icon_code" == "13n"  ]; then
            weather_icon=" "
            weather_hex="#e3e6fc"
        elif [ "$weather_icon_code" == "40d"  ]; then
            weather_icon=" "
            weather_hex="#84afdb"
        elif [ "$weather_icon_code" == "40n"  ]; then
            weather_icon=" "
            weather_hex="#84afdb"
        else 
            weather_icon=" "
            weather_hex="#adadff"
        fi
        echo "$weather_icon" >  ${cache_weather_icon}
        echo "$weather_description" > ${cache_weather_stat}
        echo "$weather_temp" > ${cache_weather_degree}
        echo "$weather_hex" > ${cache_weather_hex}
    else
        echo "Weather Unavailable" > ${cache_weather_stat}
        echo " " > ${cache_weather_icon}
        echo "-" > ${cache_weather_degree}
        echo "#adadff" > ${cache_weather_hex}
    fi
}

## Execute

## Make cache dir
if [[ ! -d "$cache_dir" ]]; then
    mkdir -p ${cache_dir}
    update_weather_data
else
    ## Update if some time has passed
    last_modification=$(stat -c %Y "$cache_weather_degree")
    current_time=$(date +%s)
    time_diff=$((current_time - last_modification))
    minutes=$((time_diff / 60))
    if [[ $minutes -ge $update_interval ]]; then
        update_weather_data
    fi
fi

## Output requeste value if any
if [[ "$1" == "--update" ]]; then # manual update
    update_weather_data
elif [[ "$1" == "--icon" ]]; then
    cat ${cache_weather_icon}
elif [[ "$1" == "--temp" ]]; then
    cat ${cache_weather_degree} | tr -d '\n' && echo "°C"
elif [[ "$1" == "--hex" ]]; then
    cat ${cache_weather_hex}
elif [[ "$1" == "--stat" ]]; then
    cat ${cache_weather_stat}
fi
